### ISSUE TITLE
No B groups being shown 

### ISSUE THREAD

**Issue by SmartKapila** [utkarsh-1905/time-table#48]
Actually sir no B groups for 1st year were being shown.

Also sir I cloned the repo to try updating 23-24 Even Sem. According to what I understood(maybe I am wrong) I found all content from Excel file is extracted by golang file genData.go and coverted to json file. But after replacing old excel file by new(Even sem) file the json file was not being updated. Even if I would delete old json there was no new json file being created after running the code.

Please may you guide me here also.

**Comment by utkarsh-1905** [comment]
to generate the the json source file, uncomment lines 22 and 23 in main.go file and run the server  `go run main.go`

**Comment by utkarsh-1905** [comment]
it's a very minor bug, there is a line error in Excel, I have fixed it and pushing it, since you raised the issue, you should get the credits, just pull the latest code, and make the JSON file using the above steps, validate the issue, and raise a PR

**Comment by utkarsh-1905** [comment]
here you go @SmartKapila

**Comment by SmartKapila** [comment]
Thank you sir very much🙏🏻 for providing me this opportunity and honour. I have created a merge request. Please do the needful.

**Comment by utkarsh-1905** [comment]
@SmartKapila I hope you have a better understanding of the project now

**Comment by SmartKapila** [comment]
> @SmartKapila I hope you have a better understanding of the project now

Yes @utkarsh-1905 sir solely due to your guidance :)
