### ISSUE TITLE
Missing lecture in Time Table

### ISSUE THREAD

**Issue by PreetinderSingh13** [utkarsh-1905/time-table#52]
**Describe the bug**
For group A32-A36 we are missing a lecture(UES101) in LP-102 between 2:40pm to 3:30pm on Thursday

**To Reproduce**
1. Go to 'https://timetable.mlsctiet.com/timetable?sheet=1ST%20YEAR%20A&classname=1%20A36'
2. There a lecture is missing

**Expected behavior**

**Screenshots**
![issue](https://github.com/utkarsh-1905/time-table/assets/132475572/ced719f4-8d59-4e57-a3e7-f3c8951e9e6b)

**Additional context**
This problem is due to missing lecture from excel provide by college, To solve please add given details to the excel.

**Comment by utkarsh-1905** [comment]
can you solve this on your own? then I'll assign this to you

**Comment by DarkCoder26** [comment]
I can try it Bhaiya
