### ISSUE TITLE
Feature for lecture class venue in all subgroups

### ISSUE THREAD

**Issue by SparshRastogi** [utkarsh-1905/time-table#8]
The current program shows the lecture venue only in the first class in a group like for example CS 6-10 have lectures combined so venue is being shown only in CS 6,it might be due to the fact that the cell for that thing is combined,it would be great if this issue is fixed

**Comment by utkarsh-1905** [comment]
Hey @SparshRastogi, can you verify that this issue is fixed with this commit ([a945454](https://github.com/utkarsh-1905/time-table/commit/a945454c0a1564251c9ed31cf1a5e26e6fd9158b)) ?

**Comment by SparshRastogi** [comment]
Yes it has been resolved
